### ISSUE TITLE
problem with the "                 ?><script data-php_error="magic JS, just ignore this!"> " in CURL

### ISSUE THREAD

**Issue by ATouhou** [bueltge/Debug-Objects#46]
Hi.
All the around 6000 chars are printed when doing an php file with getting PHP file with CURL... 
Please make a work around as having this error reporting tool included in an "global config", makes the JSON element useless.. -.-

**Comment by bueltge** [comment]
Thanks for your hint. Can you explain this, also with a example, that I can retrace the problem. Thx

**Comment by ATouhou** [comment]
I have a file , the only output in it is "  echo json_encode($finalprint); " where $finalprint is an array.
When accessing the file manually in the browser, it shows the same output no matter if I have this debugging repo activated or not.  So far, so Good.


The problem happens when I access the file through another file with curl (and file get contents)

$url = " i put the file url here ";
$ch = curl_init(); 
curl_setopt($ch, CURLOPT_URL, $url); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
curl_setopt($ch, CURLOPT_HEADER, 0); 
$data = curl_exec($ch);


when printing the results i get the "magic JS, just ignore this" error, hence the data is not received as an array anymore.   When disabling the debugging repo, it works correctly :-)...

**Comment by ATouhou** [comment]
lol I so commented in the wrong repo xD sry bout that

**Comment by bueltge** [comment]
No problem, the close button is easy to find. Best.
