### ISSUE TITLE
Call to undefined function settings_fields in class-settings.php

### ISSUE THREAD

**Issue by Leglaw** [bueltge/debug-objects#49]
PHP v5.6
WordPress v4.7.2

Post installation, this plugin breaks my Wordpress site.

```
Fatal error: Call to undefined function settings_fields() in /var/www/html/wp-content/plugins/debug-objects/inc/autoload/class-settings.php on line 237
```

May also want to respond on the plugin site as well:
https://wordpress.org/support/topic/php-fatal-error-uncaught-error-call-to-undefined-function-settings_fields/

**Comment by bueltge** [comment]
Which version do you use, the master branch from github or the release from wordpress.org?

**Comment by bueltge** [comment]
@Leglaw Can you test the current version from GitHub, the master branch?

**Comment by metaodi** [comment]
@bueltge I can confirm that this error occurs with the current master branch as well (I'm using the same WP and PHP version as @Leglaw)

**Comment by metaodi** [comment]
I guess the function is undefined because the include where it is defined have not yet happened at the time when it is called (see [this similar question on StackExchange](http://wordpress.stackexchange.com/questions/72467/oop-plugin-and-menu-call-to-undefined-function-register-setting)). Hope this helps.

**Comment by bueltge** [comment]
Have you active the plugin in a single site or Multisite?

**Comment by metaodi** [comment]
On a single site

**Comment by bueltge** [comment]
I don't have this problem in my tests. But I have change the constructor to init all required classes to load only on hook `init`. Maybe this helps you. Please test the master branch and send me feedback - thanks a lot. Best.

**Comment by metaodi** [comment]
@bueltge with the latest `master` it works for me :wink: Thanks!
