### ISSUE TITLE
Settings not saved or applied

### ISSUE THREAD

**Issue by ChristophHess** [bueltge/debug-objects#53]
When changing the settings in the backend and clicking save at first they seem to be applied. However, they neither show up when using the objects debug nor when you click save again (settings will revert back to original).

**Comment by bueltge** [comment]
Is the plugin in a Single oder Multisite mode active?

**Comment by fabiotroyli** [comment]
Actually I have the same issue. Where I can see the settings for Single or Multisite in the plugin?

**Comment by bueltge** [comment]
@fabiotroyli Have you seen the screenshots? The settings of the plugin always under the menu item 'Settings' from WordPress. Also inside the Multisite Network Admin area.
