### ISSUE TITLE
502 Gateway error: upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by simplenotezy** [bueltge/debug-objects#54]
I am getting error `upstream sent too big header while reading response header from upstream` when trying to view debug parameters.
I have tried changing buffer size as per https://stackoverflow.com/questions/23844761/upstream-sent-too-big-header-while-reading-response-header-from-upstream still same issue.

Any recommendations on what could be done?

My error:

    2019/09/30 13:09:05 [error] 62789#0: *19 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: website.test, request: "GET /product/torun-bangle-2/?debug HTTP/2.0", upstream: "fastcgi://unix:/Users/constantsolutions/.config/valet/valet.sock:", host: "website.test", referrer: "https://website.test/product/torun-bangle-2/"

**Comment by bueltge** [comment]
Please try to reduce the options of the plugin. Don't use all debug features, is too heavy fir the response. Reduce the features of the plugins inside the settings page of the plugin.
